name: Deploy Terraform Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'

env:
  TF_LOG: DEBUG
  TF_WORKING_DIR: ./terraform
  TF_VERSION: ${{ secrets.TF_VERSION }}
  TF_VAR_backend_bucket_name: ${{ secrets.BACKEND_BUCKET_NAME }}
  TF_VAR_backend_bucket_region: ${{ secrets.BACKEND_BUCKET_REGION }}
  TF_VAR_aws_acm_region: ${{ secrets.AWS_ACM_REGION }}
  TF_VAR_domain_bucket_name: ${{ secrets.DOMAIN_BUCKET_NAME }}
  TF_VAR_domain_bucket_region: ${{ secrets.DOMAIN_BUCKET_REGION }}
  TF_VAR_route53_domain_name: ${{ secrets.ROUTE53_DOMAIN_NAME }}
  TF_VAR_route53_hosted_zone_id: ${{ secrets.ROUTE53_HOSTED_ZONE_ID }}
  TF_VAR_route53_record_ttl: ${{ secrets.ROUTE53_RECORD_TTL }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  terraform_init:
    name: Terraform Init and Validate
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ secrets.TF_VERSION }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Initialize Terraform
      run: |
        terraform init \
          -backend-config="bucket=${{ secrets.BACKEND_BUCKET_NAME }}" \
          -reconfigure
      working-directory: ${{ env.TF_WORKING_DIR }}
    
    - name: Validate Terraform
      run: terraform validate
      working-directory: ${{ env.TF_WORKING_DIR }}
      timeout-minutes: 3
    
  terraform_deploy:
    name: Terraform Deploy
    runs-on: ubuntu-latest
    needs: terraform_init

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ secrets.TF_VERSION }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Initialize Terraform
      run: |
        terraform init \
          -backend-config="bucket=${{ secrets.BACKEND_BUCKET_NAME }}" \
          -backend-config="region=${{ secrets.BACKEND_BUCKET_REGION }}" \
          -reconfigure
      working-directory: ${{ env.TF_WORKING_DIR }}

    - name: Plan Terraform
      run: terraform plan
      working-directory: ${{ env.TF_WORKING_DIR }}

    - name: Apply Terraform
      run: terraform apply -auto-approve
      working-directory: ${{ env.TF_WORKING_DIR }}