name: Copy website files to S3

on:
  push:
    branches:
      - main
    paths:
      - 'my_website/**'

env:
  TF_LOG: DEBUG
  
jobs:
  copy_to_s3:
    name: Copy website files to S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync files to S3
        run: |
          aws s3 sync my_website/ s3://${{ secrets.DOMAIN_BUCKET_NAME }} --delete
